/*
1. Return the number of babies born in each of the six regions
   (NOTE: The state of MI should be in the Midwest region)
*/
-- STEP 1. ADD MISSING ROW TO REGION TABLE FOR MI STATE 
-- INSERT INTO REGIONS VALUES('MI', 'Midwest');

-- STEP 2. REGION TABLE HAVE 7 REGIONS INSTEAD OF 6 AND REASON IS TWO ROWS FOR THE SAME REGION
--         'NEW_ENGLAND' AND 'NEW ENGLAND'
-- WE CAN USE SUB QUERY TO MAKE IT ONE
DROP VIEW CLEAND_REGION_V;
CREATE OR REPLACE VIEW CLEAND_REGION_V AS
(SELECT STATE, (CASE WHEN REGION = 'NEW ENGLAND' THEN 'NEW_ENGLAND' 
                                ELSE REGION
                                END) AS REGION 
            FROM REGIONS
);
-- STEP 2. FIND NUMBER OF BABIES IN EACH REGION
SELECT REGION, SUM(BIRTHS) AS NUM_OF_BABIES
FROM NAMES T1 INNER JOIN  CLEAND_REGION_V AS T2 ON T1.STATE = T2.STATE
GROUP BY REGION
;


/*
2. Return the 3 most popular girl names and 3 most popular boy names within each region
*/
SELECT * FROM
(
	SELECT A1.REGION
		 , A1.GENDER
		 , A1.NAME
		 , ROW_NUMBER() OVER(PARTITION BY A1.REGION, A1.GENDER
							 ORDER BY A1.NUM_OF_BABIES DESC) AS POPULARITY_RANK
	FROM
	(
		SELECT T2.REGION
			 , T1.GENDER
			 , T1.NAME
			 , SUM(T1.BIRTHS) AS NUM_OF_BABIES
		FROM NAMES T1 INNER JOIN CLEAND_REGION_V T2 ON T1.STATE = T2.STATE
		GROUP BY T2.REGION, T1.GENDER, T1.NAME
	) AS A1
) AS B1
WHERE POPULARITY_RANK <= 3
;