/*
1. For each year, return the 3 most popular girl names and 3 most popular boy names
*/
SELECT * FROM
(
SELECT T1.YEAR
     , T1.GENDER
	 , T1.NAME
     , ROW_NUMBER() OVER(PARTITION BY YEAR, GENDER ORDER BY T1.NUM_OF_BABIES DESC) AS POP_RANK
FROM
(
	SELECT YEAR
		 , GENDER
		 , NAME
		 , SUM(BIRTHS) AS NUM_OF_BABIES
	FROM NAMES
	GROUP BY YEAR, GENDER, NAME
	ORDER BY YEAR, NUM_OF_BABIES DESC
) AS T1
) AS A1
WHERE POP_RANK <= 3
;

/*
2. For each decade, return the 3 most popular girl names and 3 most popular boy names
*/
SELECT * FROM
(
SELECT T1.DECADE
     , T1.GENDER
	 , T1.NAME
     , ROW_NUMBER() OVER(PARTITION BY DECADE, GENDER ORDER BY T1.NUM_OF_BABIES DESC) AS POP_RANK
FROM
(
	SELECT (CASE WHEN YEAR BETWEEN 1980 AND 1989 THEN '80\'S'
                WHEN YEAR BETWEEN 1990 AND 1999 THEN '90\'S'
                WHEN YEAR BETWEEN 2000 AND 2009 THEN '2000\'S' 
                ELSE 'NONE'
            END) AS DECADE
		 , GENDER
		 , NAME
		 , SUM(BIRTHS) AS NUM_OF_BABIES
	FROM NAMES
	GROUP BY DECADE, GENDER, NAME
	ORDER BY DECADE, NUM_OF_BABIES DESC
) AS T1
) AS A1
WHERE POP_RANK <= 3
;